[package]
name = "asteroids"
version = "0.6.2"
edition = "2024"
license = "AGPL-3.0-only"
rust-version = "1.88.0"

[dependencies]
bevy = "0.17"
bevy-inspector-egui = "0.34"
bevy_rapier2d = "0.32"
rand = "0.9"

[features]
default = ["dynamic_linking"]
dynamic_linking = ["bevy/dynamic_linking"]
debug_ui = ["bevy_rapier2d/debug-render-2d"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[profile.speedy]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3
strip = "symbols"
panic = "abort"

[profile.tiny]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "z"
strip = "symbols"
panic = "abort"
