[package]
name = "asteroids"
version = "0.3.0"
edition = "2024"

[dependencies]
bevy = "0.16"
bevy-inspector-egui = "0.32.0"
bevy_rapier2d = "0.31.0"
rand = "0.9.2"

[features]
dynamic_linking = ["bevy/dynamic_linking"]
debug_ui = ["bevy_rapier2d/debug-render-2d"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.3", features = ["wasm_js"] }

[profile.speedy]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3
strip = "symbols"
panic = "abort"

[profile.tiny]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "z"
strip = "symbols"
panic = "abort"
